### Add categories START >>>>>>>>>>>>
POST http://localhost:8080/admin/category
Authorization: Basic admin@mail.com 12345.com
Content-Type: application/json

{"name": "Phone"}

###

POST http://localhost:8080/admin/category
Authorization: Basic admin@mail.com 12345.com
Content-Type: application/json

{"name": "Leptop"}

###

POST http://localhost:8080/admin/category
Authorization: Basic admin@mail.com 12345.com
Content-Type: application/json

{"name": "Test"}

###

POST http://localhost:8080/admin/product
Authorization: Basic admin@mail.com 12345.com
Content-Type: application/json

{"name":"Samsung A10", "price": 1100.00,"category": {"id": "Phone"}}

###

POST http://localhost:8080/admin/product
Authorization: Basic admin@mail.com 12345.com
Content-Type: application/json

{"name":"MacBook Air", "price": 12000.00,"category": {"id": "Leptop"}}

###

POST http://localhost:8080/admin/category
Authorization: Basic admin@mail.com 12345.com
Content-Type: application/json

{"name": "PC"}

### Add categories END <<<<<<<<<<<<<<<<<<

### Add products START >>>>>>>>>>>>>>>>>>
POST http://localhost:8080/admin/product
Authorization: Basic admin@mail.com 12345.com
Content-Type: application/json

{"name":"Samsumg S10+", "price": 3000.00,"category": {"id": "[category_id]"}}

###

POST http://localhost:8080/admin/product
Authorization: Basic admin@mail.com 12345.com
Content-Type: application/json

{"name":"IPhone X", "price": 3500.00,"category": {"id": "Phone"}}

###

POST http://localhost:8080/admin/product
Authorization: Basic admin@mail.com 12345.com
Content-Type: application/json

{"name":"Xiaomi A3", "price": 2700.00,"category": {"id": "Phone"}}

###

POST http://localhost:8080/admin/product
Authorization: Basic admin@mail.com 12345.com
Content-Type: application/json

{"name":"MacBook Pro i9", "price": 8700.00,"category": {"id": "Leptop"}}

###

POST http://localhost:8080/admin/product
Authorization: Basic admin@mail.com 12345.com
Content-Type: application/json

{"name":"Lenovo x10", "price": 6570.00,"category": {"id": "Leptop"}}

###

POST http://localhost:8080/admin/product
Authorization: Basic admin@mail.com 12345.com
Content-Type: application/json

{"name":"iMac PRO", "price": 18350.00,"category": {"id": "PC"}}

###

POST http://localhost:8080/admin/product
Authorization: Basic admin@mail.com 12345.com
Content-Type: application/json

{"name":"ABS Master-Pro Ryzen 5 2400G", "price": 13670.00,"category": {"id": "PC"}}

### Add products END <<<<<<<<<<<<<<<<<<<<<<<


POST http://localhost:8080/admin/product
Authorization: Basic admin@mail.com 12345.com
Content-Type: application/json

{"name":"IPhone XXX", "price": 13500.00,"category": {"id": "PC"}}

### Delete product
DELETE http://localhost:8080/admin/product/5d5166208a22c87f46059ace
Authorization: Basic admin@mail.com 12345.com


### Add some category
POST http://localhost:8080/admin/category
Authorization: Basic admin@mail.com 12345.com
Content-Type: application/json

{"name": "AbraKadabra"}

### Delete category
DELETE http://localhost:8080/admin/category/e4efe69a-288d-43d4-81dd-055202bdf1e5


### Update category name
PUT http://localhost:8080/admin/category
Authorization: Basic admin@mail.com 12345.com
Content-Type: application/json

{"catId":"d4034ac5-3abc-4085-be47-3facb3afe0e6", "catName":"SomeName"}
###

### Update product price
PUT http://localhost:8080/admin/product
Authorization: Basic admin@mail.com 12345.com
Content-Type: application/json

{"prodId":"d4034ac5-3abc-4085-be47-3facb3afe0e6", "price":666.66}
###

### Update user balance
PUT http://localhost:8080/admin/user
Authorization: Basic admin@mail.com 12345.com
Content-Type: application/json

{"userId":"john@mail.com", "balance":100000.00}
###

### Get Statistics

###
GET http://localhost:8080/admin/statistic/mostPopularProducts
Authorization: Basic admin@mail.com 12345.com

###

GET http://localhost:8080/admin/statistic/mostProfitableProducts
Authorization: Basic admin@mail.com 12345.com

###

GET http://localhost:8080/admin/statistic/mostActiveUser
Authorization: Basic admin@mail.com 12345.com

###

GET http://localhost:8080/admin/statistic/mostProfitableUser
Authorization: Basic admin@mail.com 12345.com

###